import Providers from "~/common/providers";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "ImageGen",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <Providers>{children}</Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
